#!/bin/sh

echo "Compilation du serveur parallèle d'écoute des factures"
gcc src/serveur_facture.c -lsqlite3 -o exe/serveur_facture;
gcc src/facture.c -lsqlite3 -o exe/facture;
echo "Tapez par ex 'exe/facture 127.0.0.1 3201 1 electricite 10' pour ajouter une facture d'électricité"
echo "Ecoute sur le port 3201..."
exe/serveur_facture 3201

